trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*
pr:
  - master


pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    echo no | npm install -g nativescript
    ns usage-reporting disable
    ns error-reporting disable
  displayName: 'Install NativeScript CLI'

- script: |
    cd src
    npm install
    npm run ci.tslint
  displayName: 'Lint'

- script: |
    cd demo
    npm install
    ns build android --bundle --env.uglify --env.snapshot
  displayName: 'Build'

- script: |
    ./ci-tools/wait-for-emulator.sh
    cd demo
    ns test android --watch false --justlaunch
  displayName: 'Test'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'demo/app/test-reports/**/report.xml'
